### ISSUE TITLE
Unable to add package

### ISSUE THREAD

**Issue by vthommeret** [segmentio/analytics-swift#100]
**Describe the bug**

I've been trying to add this library for many days / have added other libraries via Swift Package Manager (e.g. Firebase) successfully, but have been running into issues with Segment specifically. I believe it was initially related to Segment requiring being added via SSH vs HTTPS but I've added my laptop's SSH keys to Github and believe it's working correctly (correct status in Xcode / I can clone git@github.com:segmentio/analytics-swift.git from the CLI, etc...). 

**To Reproduce**
1. Go to File → Add Packages…
2. Enter `git@github.com:segmentio/analytics-swift.git` into the "Search or Enter Package URL" field.

**Expected behavior**
Name of library and README show up. Library is added successfully.

**Observed behavior**
1. Title, readme, etc... aren't pulled. Size is displayed. (See screenshot)
2. That said, I am still able to add the library and metadata displays. (See next screenshot)
3. However once it's added to the project, I see the error `/Users/vthommeret/Code/Loopable/github.com:segmentio/analytics-swift.git: The remote repository could not be accessed. Make sure a valid repository exists at the specified location and that the correct credentials have been supplied.`

It seems like this is maybe a credential issue but it's strange that it does pull the metadata in some instances and actually does download and add the project, which previously didn't work when I didn't set up SSH key authentication.

**Screenshots**

<img width="1077" alt="Screen Shot 2021-12-03 at 10 45 17 AM" src="https://user-images.githubusercontent.com/42359/144656238-243ed7b0-031d-4bbd-8700-b8510cd654dd.png">

<img width="1092" alt="Screen Shot 2021-12-03 at 10 38 40 AM" src="https://user-images.githubusercontent.com/42359/144655397-fb41bc98-c9e9-4928-878f-c834d6d918bf.png">

<img width="607" alt="Screen Shot 2021-12-03 at 10 40 48 AM" src="https://user-images.githubusercontent.com/42359/144655702-b4f946a1-8aae-42d5-9ed9-ada7c5f69180.png">

<img width="806" alt="Screen Shot 2021-12-03 at 10 41 33 AM" src="https://user-images.githubusercontent.com/42359/144655765-3fbadd92-9065-45d5-8a46-91a8cb5b7614.png">

**Platform (please complete the following information):**

 - Library Version in use: 1.0.6
 - Platform being tested: iOS Swift app
 - Integrations in use: None yet.

**Comment by migs647** [comment]
@vthommeret I was not able to reproduce this. I created a brand new Github account (so my work account would not interfere with permissions). Instead of my normal path of creating a ssh key via: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent, I used your method by generating an access token in Github via Settings -> Developer Settings - > Personal access tokens. I generated that token with full permissions. After I signed in that way via Xcode I created a SSH key via the drop down. I saved it to my Desktop. I then created a new iOS project and added the Segment library by clicking on the Project in the Project Navigator and then the Project Target. I then clicked on Package Dependencies and clicked the `+` button to add. I used the url I copied from your pose `git@github.com:segmentio/analytics-swift.git` and was able to successfully add both Segment and Sovran. I made sure the same Branch / Main option was selected when adding. 

I would make sure you are on the latest Xcode version. I would also recommend deleting your Derived Data folder in `/Users/vthommeret/Library/Developer/Xcode/DerivedData`. If nothing else, perhaps creating a new id_rsa.pub file or new Access Token may be beneficial. It is also possible your Access Token has expired, please double check that as well.

**Comment by vthommeret** [comment]
Thanks for your thorough repro steps! I tried using a brand new iOS app project, creating a brand new SSH key (which Xcode verified and was uploaded to GitHub), deleted my Derived Data, build and clean, created a new access token, and everything still failed.

One thing that stood out to me in the error message: `/Users/vthommeret/Code/Loopable/github.com:segmentio/analytics-swift.git` is that it seemed to be trying to load the remote package as a local package. This is what my other repository URL's looked like in `project.pbxproj`:

1. `repositoryURL = "https://github.com/firebase/firebase-ios-sdk.git";`
2. `repositoryURL = "https://github.com/dmytro-anokhin/url-image.git";`
3. `repositoryURL = "github.com:segmentio/analytics-swift.git";`

I think because there's no protocol, it was treating it as a local package. Which is strange because as you can see in the screenshots, it actually pulled the remote project and the name of it "Segment". If I tried to manually enter `https://github.com/segmentio/analytics-swift.git` into the UI nothing showed up. That said when I manually edited my `project.pbxproj` file to use `repositoryURL = "https://github.com/segmentio/analytics-swift.git";` then it successfully recognized the package and let me `import Segment` into my project.

I'm not sure why it works for your set up — I suspect it's an Xcode issue (possibly related to #32) that Swift Package Manager has some quirks around handling SSH vs. HTTPS URL's, but at least I have a working solution for now.
