### ISSUE TITLE
Traits dictionary not included in event tracking

### ISSUE THREAD

**Issue by YuriAR** [segmentio/analytics-swift#180]
**Describe the bug**
I just migrated my app from the old analytics-ios and noticed that the `traits` dictionary is missing from all of the track event calls.  It used to be present within the `context` dictionary, but no more.

Digging deeper into it, I saw that you have a unit test called `testUserIdAndTraitsPersistCorrectly` that asserts the following:

```swift
let trackTraits = trackEvent?.context?.dictionaryValue?["traits"] as? [String: Any]
XCTAssertNil(trackTraits)
```

which leads me to believe this was removed intentionally. Is that the case? If so, isn't the intention of the identity call to make sure all the following track events are correctly identified? Is there another approach we should follow to get the traits data? Anything we need to enable in the SDK?

**To Reproduce**
1. Identify a user
2. Trigger any event tracking
3. See error

**Expected behavior**
I expected the `traits` dictionary to be present within the context dictionary.

**Platform (please complete the following information):**
 - Library Version in use: 1.3.3
 - Platform being tested: iOS 16
 - Integrations in use: -

**Comment by sean86** [comment]
+1 to this, we are having the same issue

**Comment by sean86** [comment]
@YuriAR fyi we were able to fix this issue by adding this plugin https://github.com/segmentio/analytics-swift/pull/181/files

Its still weird to me that this default functionality was removed, and the biggest issue is that it doesn't seem to be mentioned in the migration guide

**Comment by bsneed** [comment]
@YuriAR @sean86 this removal was intentional.  It's a new SDK and we removed problematic parts and this was one of them.  It's no longer necessary w/ the new plugin architecture.  You can write a simple plugin to accomplish the same task that's much more maintainable rather than having it at each call site.  Our internal review showed that it wasn't in widespread use and thus was omitted from the migration guide.  Happy to help you guys write something equivalent if you can share some more details about how you're using it.

**Comment by cprince-foreflight** [comment]
It seems like this different default behavior should be included in your migration documentation. E.g., I don't see "traits" referenced in https://segment.com/docs/connections/sources/catalog/libraries/mobile/apple/migration/
