### ISSUE TITLE
RecordScreenViews and trackPushNotifications

### ISSUE THREAD

**Issue by benMohamed** [segmentio/analytics-swift#193]
I couldn't locate two properties, '**trackPushNotifications**' and '**RecordScreenViews**,' in the Configuration class. I checked the documentation at [https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#automatic-screen-tracking ](https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#automatic-screen-tracking )where they are mentioned.

**Comment by bsneed** [comment]
That's the docs for the analytics-ios library.  Those options aren't in the analytics-swift library.  They've been replaced by plugins since customers tend to want to customize behavior around these two areas.

Swift Docs: https://segment.com/docs/connections/sources/catalog/libraries/mobile/swift-ios/

Example Notification tracking plugin: https://github.com/segmentio/analytics-swift/blob/main/Examples/other_plugins/NotificationTracking.swift

Example Screen tracking plugin: https://github.com/segmentio/analytics-swift/blob/main/Examples/other_plugins/UIKitScreenTracking.swift
