### ISSUE TITLE
TrackDeeplinks property

### ISSUE THREAD

**Issue by benMohamed** [segmentio/analytics-swift#194]
Hello,
I have noticed that changing the value of '`trackDeeplinks`' to true or false does not have any effect. 
Upon examining the code, I found that it only stores a boolean value.

**Comment by bsneed** [comment]
Looks like that was an oversight on our part by not removing it.  Between UIKit, SwiftUI and some nuances of specific platforms we felt that this was better done manually by developers since we couldn't really do it automatically across the board anymore.  Please see the `openURL` method on the analytics class.  I'll make a PR to remove this flag.
