### ISSUE TITLE
Asynchronous mechanism for enrichment in Plugins

### ISSUE THREAD

**Issue by malcommac** [segmentio/analytics-swift#234]
**Is your feature request related to a problem? Please describe.**

Hi, we are exploring the Plugin architecture to enrich events before sending them to Segment. 

Specifically, we have an endpoint that provides additional data about an event that we can include with the event. This endpoint call is asynchronous, while the Plugin transformation function is synchronous `(func execute<T: RawEvent>(event: T?) -> T?)`.

Is this scenario supported by Segment?

**Describe the solution you'd like**

An asynchrous mechanism to enrich events from inside the `Plugin` architecture.

**Describe alternatives you've considered**

We are also exploring the possibility of using a synchronous network request within the function, but we are unsure if it could interfere with other parts of the SDK. 

Specifically, it seems that we would lose the ability to use the batching feature of the SDK.

**Comment by bsneed** [comment]
Hi @malcommac,

No, you shouldn't do sync network calls in your plugin methods.  The entire event pipeline will stall since it all runs in the same FIFO queue.  You should make your async network call, store the results you want and as events flow through, used the value returned from the previous async call to enrich your event.  Let me know if your use case is more nuanced than what I'm imaging and I'll come up with something to get you going.
