### ISSUE TITLE
Documentation for track, screen, and identify regarding properties isn't fully accurate + unexpected debug crash 

### ISSUE THREAD

**Issue by cprince-foreflight** [segmentio/analytics-swift#254]
**Describe the bug**
The documentation [here](https://segment.com/docs/connections/sources/catalog/libraries/mobile/apple/implementation/#track) suggests that any properties passed to `track` that are `Codable` will be successfully logged. This isn't fully accurate. 

Instead, the properties must be [able to be passed to the `JSON` init method](https://github.com/segmentio/analytics-swift/blob/ad34912ad10478f3308d30b68a7119fcef68981f/Sources/Segment/Events.swift#L20). Further, if that `JSON` init method throws an error due to type issues with the passed properties, then with debug builds an assert causes a crash.

With our app, I don't want use of Segment to cause a debug crash.

This also is true for screen and identify calls.

**To Reproduce**
As indicated above.

**Expected behavior**
1) I think the docs should better reflect the actual constraints on the property types.
2) Library users should be given the option about whether they want these debug asserts to cause crashes. E.g., this should be configurable.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - Library Version in use: 1.4.7
 - Platform being tested: iOS

**Additional context**
N/A

**Comment by cprince-foreflight** [comment]
I see now that the type part of my statement above more strongly applies to [the untyped signature alternative](https://github.com/segmentio/analytics-swift/blob/ad34912ad10478f3308d30b68a7119fcef68981f/Sources/Segment/Events.swift#L145).

I still believe that the library caller should have control over whether such typing issues cause crashes in debug builds.

**Comment by bsneed** [comment]
They will be successfully logged, provided they're expressible in JSON.  You're getting the assert in your debug build because the params you're supplying are NOT expressible in JSON.  This assert isn't going to be removed, and we're not going to make it an option.  It's there for you to know that you need to fix the parameters or stop sending them because they will not show up in Segment.

The docs you reference show conformance to Codable, which seems to be a pretty strong indicator of what the type requirements are.
