### ISSUE TITLE
Adding SPM dependency to Xcode with default "up to 1.0.0" results in package resolution error due to sovran URL

### ISSUE THREAD

**Issue by JetForMe** [segmentio/analytics-swift#32]
**Describe the bug**
When you add `analytics-swift` to an Xcode project, the default is to have it fetch "up to next major from <current version>". Unfortunately, tag 1.0.0's Package.swift contains a reference to Sovran `git@github.com:segmentio/Sovran-Swift.git`, which Xcode fails to pull, getting

```
x-swift-package-repository-authentication://?scm=com.apple.dt.Xcode.sourcecontrol.Git&url=git@github.com:segmentio/Sovran-Swift.git#error=-1005 Authentication failed because the credentials were missing
```
Your `main` branch has an updated `Package.swift`. You should probably make a new tag in git with that change.

**To Reproduce**
1. Add `analytics-swift` using default Xcode version selection
2. Be sad

**Comment by migs647** [comment]
Thanks for calling this out @JetForMe. I'll take a look at this. Sovran is needed, we will look at auth issues with that. Will update.

**Comment by migs647** [comment]
@JetForMe I was able to replicate your issue. You need to set up your ssh keys with github. I tested on a fresh user account without any ssh keys and ran into your issue. Unfortunately, even though our package.swift is using https and use the https analytics-swift portion, Xcode _forces_ Sovran to a ssh format .. ie git@github.com:segmentio/analytics-swift.git. Once I added my SSH key, it works as intended. Tested on Xcode 13 and Xcode 12.

Please use https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh in order to add your ssh key.

**Comment by JetForMe** [comment]
I'm not sure it's correct that Xcode forces Sovran to use `git@…`. I'm currently using a specific git commit hash to pull from your main branch, and it works just fine. In that branch, your `Package.swift` refers to Sovran using `"https://github.com/segmentio/Sovran-Swift.git"`

Requiring setting up SSH keys makes build automation that much harder to deal with.

**Comment by bsneed** [comment]
@JetForMe let me know if the 1.0.2 that just got tagged solves it for you.

**Comment by bsneed** [comment]
Gonna assume the answer is "YES" here. :D

**Comment by JetForMe** [comment]
Yes! I'm so sorry. I had this message flagged for weeks (months!) and got so busy at work, I forgot why I flagged it, but kept thinking I didn't have time to deal with it. Thank you for the rapid fix!.

**Comment by bsneed** [comment]
No worries at all!  My pleasure.  :high-five:
