### ISSUE TITLE
Amplitude session id constantly -1

### ISSUE THREAD

**Issue by lilidotshi** [segmentio/analytics-swift#365]
**Describe the bug**
The session ID is not being linked properly with amplitude. 

**To Reproduce**
1. Integrate Amplitude plugin by following the [examples](https://github.com/segmentio/analytics-swift/blob/main/Examples/apps/DestinationsExample/DestinationsExample/AppDelegate.swift)
2. Track some events
3. In amplitude, see that the events are not being logged with a valid session id, even though it is being set within the AmplitudeSession plugin. All the session ids are -1.

**Expected behavior**
events should be connected via a session id, right now they are not connected.

**Screenshots**

**Platform (please complete the following information):**
 - Library Version in use: Analytics-Swift 1.6.1, Analytics-Swift-Amplitude 1.4.3
 - Platform being tested: iOS
 - Integrations in use: Amplitude

**Additional context**
Amplitude also indicates that these events are being sent by WebKit605, but they are coming from the SDK.

![Screenshot 2024-09-25 at 12 49 58 PM](https://github.com/user-attachments/assets/fb594f33-6c5a-4d02-8c04-4095540d6c2e)

**Comment by bsneed** [comment]
Hi @lilidotshi,

The amplitude session plugin (Analytics-Swift-Amplitude) sends the amplitude sessionID to segment, and the data is then sent from segment to amplitude, not from the SDK itself.  Since I can't view your workspace to troubleshoot and it's not an analytics-swift issue, I'd recommend you reach out to friends@segment.com for support.  Feel free to reference this ticket when talking to them.
